from __future__ import annotations

from collections import Counter
from typing import Any

# UI status vocabulary is deliberately product-facing and conservative.
# `ui_connected` means this local PWA has a working surface today.
# `backend_ready` means concrete code/tests exist but this PWA still needs wiring.
# `partial` means a material capability exists but is not complete end to end.
# `external_gate` needs credentials, broker evidence, elapsed forward time or approval.
# `pending` means the feature is not implemented sufficiently to advertise as working.
CAPABILITIES: tuple[dict[str, Any], ...] = (
    {
        "id": "command_center",
        "group": "Core",
        "name": "Owner Command Center",
        "status": "ui_connected",
        "description": "Local installable owner cockpit with runtime controls and truthful feature visibility.",
        "evidence": ["aura/webapp/server.py", "aura/interface/web_command_center_v2.py"],
    },
    {
        "id": "mobile_pwa",
        "group": "Core",
        "name": "Desktop / Mobile PWA",
        "status": "ui_connected",
        "description": "Installable local-first web app shell for desktop and mobile browsers.",
        "evidence": ["aura/webapp/static/manifest.webmanifest", "aura/webapp/static/sw.js"],
    },
    {
        "id": "market_scanner",
        "group": "Market Intelligence",
        "name": "Multi-market / Multi-timeframe Scanner",
        "status": "backend_ready",
        "description": "Broad scanning and opportunity ranking across connected markets and timeframes.",
        "evidence": ["aura/runtime/scanner.py", "aura/runtime/opportunity_radar.py", "aura/markets/universe.py"],
    },
    {
        "id": "market_data_quality",
        "group": "Market Intelligence",
        "name": "Point-in-time Data Quality",
        "status": "backend_ready",
        "description": "Freshness, sequence, gap, duplicate, future-data and cross-feed safety gates.",
        "evidence": ["aura/data/quality.py", "aura/data/cross_feed.py"],
    },
    {
        "id": "technical_intelligence",
        "group": "Market Intelligence",
        "name": "Technical Intelligence",
        "status": "backend_ready",
        "description": "EMA, RSI, MACD, Bollinger, Keltner, ATR and related technical evidence.",
        "evidence": ["aura/agents/specialists.py", "aura/strategy/features.py"],
    },
    {
        "id": "smc_ict",
        "group": "Market Intelligence",
        "name": "SMC / ICT Structure",
        "status": "backend_ready",
        "description": "Liquidity sweep, BOS/CHoCH, FVG and structural evidence primitives.",
        "evidence": ["aura/agents/specialists.py", "aura/research/strategy_factory.py"],
    },
    {
        "id": "volume_vwap",
        "group": "Market Intelligence",
        "name": "Volume / VWAP Intelligence",
        "status": "backend_ready",
        "description": "VWAP, relative volume, OBV/VPT and participation context.",
        "evidence": ["aura/agents/specialists.py"],
    },
    {
        "id": "options_intelligence",
        "group": "Market Intelligence",
        "name": "Options / Volatility Intelligence",
        "status": "backend_ready",
        "description": "PCR, IV, Greeks, liquidity and option-chain context where broker data supports it.",
        "evidence": ["aura/options/intelligence.py", "aura/data/dhan_options.py"],
    },
    {
        "id": "macro_news",
        "group": "Market Intelligence",
        "name": "Live News / Macro Context",
        "status": "backend_ready",
        "description": "Trusted public intelligence with provenance and time-aware ingestion.",
        "evidence": ["aura/data/free_intelligence.py", "aura/data/intelligence_service.py", "aura/knowledge/firewall.py"],
    },
    {
        "id": "forecasting",
        "group": "Market Intelligence",
        "name": "Probabilistic Forecasting",
        "status": "backend_ready",
        "description": "Calibrated forecast/ensemble layer. Outputs are probabilities, not guaranteed predictions.",
        "evidence": ["aura/forecast/", "aura/agents/forecast_specialist.py"],
    },
    {
        "id": "cross_market",
        "group": "Market Intelligence",
        "name": "Cross-market Context",
        "status": "backend_ready",
        "description": "Cross-asset confirmation and contextual evidence for supported feeds.",
        "evidence": ["aura/agents/specialists.py"],
    },
    {
        "id": "regime_engine",
        "group": "Market Intelligence",
        "name": "Regime / Chop / Volatility State",
        "status": "backend_ready",
        "description": "Trend/range/chop and volatility regime awareness used by scanners and agents.",
        "evidence": ["aura/agents/specialists.py", "aura/models/drift.py"],
    },
    {
        "id": "ai_council",
        "group": "AI & Reasoning",
        "name": "Multi-model AI Council",
        "status": "backend_ready",
        "description": "Concurrent local/provider model council with structured evidence and reliability routing.",
        "evidence": ["aura/agents/ai_council.py", "aura/agents/adaptive_model_router.py", "aura/ai/free_models.py"],
    },
    {
        "id": "specialist_agents",
        "group": "AI & Reasoning",
        "name": "Specialist Agent Team",
        "status": "backend_ready",
        "description": "Technical, structure, volume, forecast, options, macro, cross-market, regime and execution roles.",
        "evidence": ["aura/agents/specialists.py", "aura/agents/external_specialists.py"],
    },
    {
        "id": "adversarial_reasoning",
        "group": "AI & Reasoning",
        "name": "Bull / Bear / Counterfactual Review",
        "status": "backend_ready",
        "description": "Adversarial deliberation captures disagreement and invalidation before decisions.",
        "evidence": ["aura/agents/deliberation.py"],
    },
    {
        "id": "ceo_orchestrator",
        "group": "AI & Reasoning",
        "name": "CEO Decision Orchestrator",
        "status": "backend_ready",
        "description": "Reliability-weighted synthesis of specialist evidence into auditable intent.",
        "evidence": ["aura/agents/orchestrator.py", "aura/agents/service.py"],
    },
    {
        "id": "explainability",
        "group": "AI & Reasoning",
        "name": "Decision Evidence / Explainability",
        "status": "backend_ready",
        "description": "Structured agent evidence, rationale, opposition, abstentions and source lineage.",
        "evidence": ["aura/agents/models.py", "aura/agents/audit.py", "aura/lineage/decision.py"],
    },
    {
        "id": "aura_chat",
        "group": "AI & Reasoning",
        "name": "AURA Owner Chat",
        "status": "partial",
        "description": "Authenticated command routing exists; full local PWA integration is being unified here.",
        "evidence": ["aura/interface/command_center.py", "aura/interface/web_command_center_v2.py"],
    },
    {
        "id": "browser_voice",
        "group": "AI & Reasoning",
        "name": "Browser Voice Input",
        "status": "backend_ready",
        "description": "Browser speech input and voice alert contracts exist; support depends on browser/platform.",
        "evidence": ["aura/interface/web_command_center_v2.py", "aura/interface/voice_alerts.py"],
    },
    {
        "id": "wake_word",
        "group": "AI & Reasoning",
        "name": "Always-on 'Hi AURA' Wake Word",
        "status": "pending",
        "description": "Native/offline always-on wake word remains a future client capability.",
        "evidence": [],
    },
    {
        "id": "risk_engine",
        "group": "Trading & Risk",
        "name": "Independent Risk Engine",
        "status": "backend_ready",
        "description": "Deterministic veto/resizing authority independent of AI opinions.",
        "evidence": ["aura/risk/engine.py", "aura/core/pipeline.py"],
    },
    {
        "id": "kill_switch",
        "group": "Trading & Risk",
        "name": "Emergency Kill / Risk Freeze",
        "status": "ui_connected",
        "description": "Local emergency lock plus financial risk-engine kill switch visibility.",
        "evidence": ["aura/webapp/server.py", "aura/risk/engine.py"],
    },
    {
        "id": "portfolio_ledger",
        "group": "Trading & Risk",
        "name": "Portfolio Ledger / P&L",
        "status": "backend_ready",
        "description": "Cash, positions, realized/unrealized P&L, fees and exposure source of truth.",
        "evidence": ["aura/portfolio/ledger.py"],
    },
    {
        "id": "order_state",
        "group": "Trading & Risk",
        "name": "Order State Machine",
        "status": "backend_ready",
        "description": "Idempotent order lifecycle, partial-fill VWAP and overfill protection.",
        "evidence": ["aura/execution/state.py"],
    },
    {
        "id": "reconciliation",
        "group": "Trading & Risk",
        "name": "Broker Reconciliation",
        "status": "backend_ready",
        "description": "Broker/local order and position reconciliation with divergence freezes.",
        "evidence": ["aura/execution/reconciliation.py", "aura/persistence/recovery.py"],
    },
    {
        "id": "manual_demo_trading",
        "group": "Trading & Risk",
        "name": "Manual DEMO Trading Desk",
        "status": "partial",
        "description": "A no-send protected BUY/SELL broker preview is connected; manual order submission remains gated.",
        "evidence": ["aura/webapp/static/mt5-bridge.js", "aura/webapp/server_v3.py", "aura/execution/mt5_protected_demo.py"],
    },
    {
        "id": "autonomous_demo",
        "group": "Trading & Risk",
        "name": "Protected Autonomous MT5 DEMO",
        "status": "ui_connected",
        "description": "Risk-approved autonomous DEMO runtime with native SL/TP protection and local start/stop.",
        "evidence": ["aura/runtime/mt5_autonomous_demo.py", "aura/execution/mt5_protected_demo.py"],
    },
    {
        "id": "paper_trading",
        "group": "Trading & Risk",
        "name": "Paper Trading",
        "status": "backend_ready",
        "description": "Deterministic paper broker and autonomous paper runtimes share core decision paths.",
        "evidence": ["aura/execution/paper.py", "aura/runtime/autonomous_paper.py"],
    },
    {
        "id": "live_money",
        "group": "Trading & Risk",
        "name": "Controlled Live-money Canary",
        "status": "external_gate",
        "description": "Intentionally locked until forward broker evidence, release gates and explicit human approval pass.",
        "evidence": ["aura/ops/release_gate.py", "aura/ops/preflight.py"],
    },
    {
        "id": "fund_transfer",
        "group": "Trading & Risk",
        "name": "Fund Transfer",
        "status": "blocked",
        "description": "Permanently absent from AURA owner/developer automation authority.",
        "evidence": ["aura/webapp/server.py"],
    },
    {
        "id": "withdrawal",
        "group": "Trading & Risk",
        "name": "Withdrawal",
        "status": "blocked",
        "description": "Permanently absent from AURA owner/developer automation authority.",
        "evidence": ["aura/webapp/server.py"],
    },
    {
        "id": "strategy_library",
        "group": "Research & Algo",
        "name": "Strategy Library / Factory",
        "status": "backend_ready",
        "description": "Immutable strategy blueprints and bounded component factory.",
        "evidence": ["aura/research/strategy_factory.py", "aura/research/lifecycle.py"],
    },
    {
        "id": "ai_strategy_architect",
        "group": "Research & Algo",
        "name": "AI Strategy Architect",
        "status": "backend_ready",
        "description": "Local AI can propose allow-listed research components without risk/broker authority.",
        "evidence": ["aura/research/ai_strategy_architect.py"],
    },
    {
        "id": "algo_studio",
        "group": "Research & Algo",
        "name": "One-click Algo Studio",
        "status": "ui_connected",
        "description": "Owner-selected safe strategy components compile into an immutable RESEARCH algo candidate; deployment remains gated.",
        "evidence": ["aura/research/strategy_factory.py", "aura/research/blueprint_compiler.py", "aura/webapp/server.py"],
    },
    {
        "id": "backtest",
        "group": "Research & Algo",
        "name": "Causal Backtesting",
        "status": "backend_ready",
        "description": "Event-driven backtests with causal next-bar semantics and shared strategy paths.",
        "evidence": ["aura/backtest/engine.py", "aura/backtest/multi_engine.py"],
    },
    {
        "id": "walk_forward",
        "group": "Research & Algo",
        "name": "Purged Walk-forward Validation",
        "status": "backend_ready",
        "description": "Leakage-aware out-of-sample validation before promotion.",
        "evidence": ["aura/research/robustness.py"],
    },
    {
        "id": "monte_carlo",
        "group": "Research & Algo",
        "name": "Monte Carlo / Robustness",
        "status": "backend_ready",
        "description": "Block-bootstrap and robustness evidence for candidate strategies.",
        "evidence": ["aura/research/robustness.py"],
    },
    {
        "id": "holdout",
        "group": "Research & Algo",
        "name": "Sealed Holdout",
        "status": "backend_ready",
        "description": "Sealed holdout protection against tuning to final validation data.",
        "evidence": ["aura/research/holdout.py"],
    },
    {
        "id": "parameter_stability",
        "group": "Research & Algo",
        "name": "Parameter Stability",
        "status": "backend_ready",
        "description": "Tests whether an edge survives around nearby parameter choices.",
        "evidence": ["aura/research/parameter_stability.py"],
    },
    {
        "id": "regime_validation",
        "group": "Research & Algo",
        "name": "Regime Validation",
        "status": "backend_ready",
        "description": "Measures candidate behavior across distinct market regimes.",
        "evidence": ["aura/research/regime_validation.py"],
    },
    {
        "id": "autonomous_lab",
        "group": "Research & Algo",
        "name": "Autonomous Strategy Lab",
        "status": "backend_ready",
        "description": "Bounded hypothesis → candidate → validation → paper loop that cannot self-approve live deployment.",
        "evidence": ["aura/research/autonomous_strategy_lab.py", "aura/research/autonomy.py"],
    },
    {
        "id": "self_learning",
        "group": "Learning",
        "name": "Outcome-based Self-learning",
        "status": "backend_ready",
        "description": "Forward-only learning from executed trades, missed opportunities and failures.",
        "evidence": ["aura/evolution/online_learning.py", "aura/evolution/opportunity_audit.py"],
    },
    {
        "id": "shadow_learning",
        "group": "Learning",
        "name": "Shadow Outcomes / Challengers",
        "status": "backend_ready",
        "description": "Shadow outcomes score alternatives without granting them execution authority.",
        "evidence": ["aura/evolution/shadow_outcomes.py", "aura/research/live_shadow_strategy_lab.py"],
    },
    {
        "id": "champion_challenger",
        "group": "Learning",
        "name": "Champion / Challenger Governance",
        "status": "backend_ready",
        "description": "Measured promotion/demotion of strategy/model candidates under governance.",
        "evidence": ["aura/research/lifecycle.py", "aura/models/registry.py"],
    },
    {
        "id": "cognitive_memory",
        "group": "Learning",
        "name": "Cognitive Memory",
        "status": "backend_ready",
        "description": "Working/episodic-style memory primitives for governed contextual learning.",
        "evidence": ["aura/memory/cognitive.py", "aura/knowledge/local_corpus.py"],
    },
    {
        "id": "knowledge_rag",
        "group": "Learning",
        "name": "Knowledge / RAG Firewall",
        "status": "backend_ready",
        "description": "Trusted-source retrieval with provenance, point-in-time controls and contradiction handling.",
        "evidence": ["aura/knowledge/firewall.py", "aura/knowledge/retrieval.py"],
    },
    {
        "id": "mt5_connector",
        "group": "Brokers & Data",
        "name": "MetaTrader 5 / Exness DEMO",
        "status": "ui_connected",
        "description": "Local Windows MT5 DEMO market data and protected execution path.",
        "evidence": ["aura/data/mt5_demo.py", "aura/execution/mt5_demo_broker.py"],
    },
    {
        "id": "dhan_connector",
        "group": "Brokers & Data",
        "name": "Dhan",
        "status": "external_gate",
        "description": "Indian-market data/paper foundations exist; user credentials and account validation are required.",
        "evidence": ["aura/data/dhan_live.py", "aura/execution/dhan_sandbox.py"],
    },
    {
        "id": "angel_one_connector",
        "group": "Brokers & Data",
        "name": "Angel One SmartAPI",
        "status": "external_gate",
        "description": "Read/order-book/position foundations exist; submit/cancel remains validation-gated.",
        "evidence": ["aura/execution/angel_one.py"],
    },
    {
        "id": "binance_connector",
        "group": "Brokers & Data",
        "name": "Binance",
        "status": "backend_ready",
        "description": "Public/test-oriented market-data foundations for crypto research.",
        "evidence": ["aura/data/binance.py"],
    },
    {
        "id": "kraken_connector",
        "group": "Brokers & Data",
        "name": "Kraken",
        "status": "backend_ready",
        "description": "Public crypto feed foundations for BTC/ETH and related research.",
        "evidence": ["aura/data/kraken.py"],
    },
    {
        "id": "oanda_connector",
        "group": "Brokers & Data",
        "name": "OANDA",
        "status": "external_gate",
        "description": "v20 practice/live read-only market-data connector; credentials required.",
        "evidence": ["aura/data/oanda.py"],
    },
    {
        "id": "telegram_alerts",
        "group": "Automation",
        "name": "Telegram Alerts",
        "status": "external_gate",
        "description": "Outbound delivery exists and requires operator bot credentials/destination validation.",
        "evidence": ["aura/interface/alerts.py"],
    },
    {
        "id": "whatsapp_alerts",
        "group": "Automation",
        "name": "WhatsApp Alerts",
        "status": "pending",
        "description": "Provider/API integration and delivery receipts are not yet implemented.",
        "evidence": [],
    },
    {
        "id": "system_health",
        "group": "Operations",
        "name": "Health / Preflight / Release Gates",
        "status": "backend_ready",
        "description": "Fail-closed health, preflight and production release evidence gates.",
        "evidence": ["aura/ops/health.py", "aura/ops/preflight.py", "aura/ops/release_gate.py"],
    },
    {
        "id": "audit_lineage",
        "group": "Operations",
        "name": "Audit / Decision Lineage",
        "status": "backend_ready",
        "description": "Decision, financial event and research lineage for reproducibility and review.",
        "evidence": ["aura/lineage/decision.py", "aura/persistence/wal.py"],
    },
    {
        "id": "developer_ai",
        "group": "Owner & Developer",
        "name": "Developer / Self-repair AI",
        "status": "backend_ready",
        "description": "Owner-gated monitor/propose/sandbox-validate development changes; no automatic merge/deploy.",
        "evidence": ["aura/maintenance/monitor.py", "aura/maintenance/change_control.py", "aura/maintenance/openai_developer.py"],
    },
    {
        "id": "financial_corrections",
        "group": "Owner & Developer",
        "name": "Audited Financial Corrections",
        "status": "backend_ready",
        "description": "Append-only reporting corrections without rewriting broker truth or original fills.",
        "evidence": ["aura/maintenance/financial_corrections.py"],
    },
    {
        "id": "owner_authority",
        "group": "Owner & Developer",
        "name": "Full Owner Governance",
        "status": "partial",
        "description": "Owner authorization/change-control contracts exist; a unified PWA owner console is being connected.",
        "evidence": ["aura/maintenance/authority.py", "aura/interface/command_center.py"],
    },
)


def capability_catalog() -> dict[str, Any]:
    items = [dict(item) for item in CAPABILITIES]
    counts = Counter(str(item["status"]) for item in items)
    groups: dict[str, list[dict[str, Any]]] = {}
    for item in items:
        groups.setdefault(str(item["group"]), []).append(item)
    return {
        "version": 2,
        "truth_policy": (
            "Only ui_connected features should look immediately operable in this PWA. "
            "backend_ready features have concrete repository evidence but may still need UI/runtime wiring. "
            "external_gate and pending features must never be presented as already working."
        ),
        "release_boundary": "PAPER_DEMO_RESEARCH; UNRESTRICTED_LIVE_MONEY_LOCKED",
        "counts": dict(sorted(counts.items())),
        "groups": groups,
        "items": items,
    }
